"""new fields in user model

Revision ID: c4b2cd46f3da
Revises: 95649981bcdd
Create Date: 2020-02-14 16:44:53.643406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b2cd46f3da'
down_revision = '95649981bcdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('date_joined', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'date_joined')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
